CREATE TABLE [dbo].[SERVICE_REQUESTS_TEMP_INS5_0]
(
[BATCHID] [int] NOT NULL IDENTITY(1, 1),
[SERVICEREQUESTID] [int] NOT NULL,
[SERVICEID] [int] NOT NULL,
[RECSTS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BATCHNUM] [int] NULL
) ON [PRIMARY]
GO
