
BEGIN TRANSACTION

BEGIN TRY

IF EXISTS (

SELECT 1

FROM INFORMATION_SCHEMA.COLUMNS

WHERE (TABLE_SCHEMA = 'dbo'

AND TABLE_NAME = 'SERVICE_REQUESTS'

AND COLUMN_NAME = 'SERVICEID')

INTERSECT

SELECT 1

FROM INFORMATION_SCHEMA.COLUMNS

WHERE

(TABLE_SCHEMA = 'dbo'

AND TABLE_NAME = 'SERVICE_REQUESTS'

AND COLUMN_NAME = 'RECSTS')

)

BEGIN

IF OBJECT_ID('dbo.SERVICE_REQUESTS_TEMP_INS5_0') IS NOT NULL

BEGIN

Print 'dbo.SERVICE_REQUESTS_TEMP_INS5_0 already exists - remove it!';

DROP TABLE dbo.SERVICE_REQUESTS_TEMP_INS5_0;

END;

CREATE TABLE dbo.SERVICE_REQUESTS_TEMP_INS5_0 (

BATCHID INT IDENTITY(1,1),

SERVICEREQUESTID INT NOT NULL,

SERVICEID INT NOT NULL,

RECSTS VARCHAR(1),

BATCHNUM INT

);

INSERT INTO dbo.SERVICE_REQUESTS_TEMP_INS5_0(SERVICEREQUESTID, SERVICEID, RECSTS, BATCHNUM)

SELECT SERVICEREQUESTID, SERVICEID, RECSTS, JSON_VALUE(PARM_JSON, '$.bATCHNUM') FROM dbo.SERVICE_REQUESTS

END

COMMIT TRANSACTION

END TRY

BEGIN CATCH

IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

PRINT 'The database update failed creating temporary table SERVICE_REQUESTS_TEMP_INS5_0';

END CATCH